.github/workflows/trivy.yml
Added Trivy to scan helm charts.
=> Add Trivy scanner workflow

charts/erpc/Chart.yaml, charts/erpc/README.md, charts/erpc/templates/ingress.yaml, charts/erpc/values.yaml
- feat: add ingress for erpc metrics endpoint
=> feat: add ingress for the erpc metrics endpoint

charts/generic-app/Chart.yaml, charts/generic-app/README.md, charts/generic-app/templates/deployment.yaml, charts/generic-app/templates/statefulset.yaml, charts/generic-app/values.deploy.yaml, charts/generic-app/values.sts.yaml
- fix: remove duplicated name field from init container
- chore: removed duplicated security context from example files
=> fix: duplicated name field

charts/aztec-validator/Chart.yaml, charts/aztec-validator/README.md, charts/aztec-validator/templates/service.yaml, charts/aztec-validator/templates/statefulset.yaml, charts/aztec-validator/values.yaml
=> feat: add http service

charts/erpc/Chart.yaml, charts/erpc/README.md, charts/erpc/templates/configmap.yaml, charts/erpc/templates/deployment.yaml, charts/erpc/templates/service.yaml, charts/erpc/templates/servicemonitor.yaml, charts/erpc/values.yaml
=> feat: add service monitor

charts/erpc/Chart.yaml, charts/erpc/README.md, charts/erpc/templates/servicemonitor.yaml, charts/erpc/values.yaml
fix: use correct value for service monitor port
=> fix: use correct value for service monitor port

charts/validators/Chart.yaml, charts/validators/README.md, charts/validators/templates/_helpers.tpl, charts/validators/templates/validate.yaml, charts/validators/values.yaml
- feat: add validation
- remove: w3s hardcoded helper based on label
=> fix w3s endpoint, remove label

charts/aztec-sequencer/Chart.yaml, charts/aztec-sequencer/README.md, charts/aztec-sequencer/files/init.sh
- feat: remove command from init.sh
=> feat: remove command from init file

charts/generic-app/Chart.yaml, charts/generic-app/README.md, charts/generic-app/README.md.gotmpl, charts/generic-app/templates/deployment.yaml, charts/generic-app/values.deploy.yaml
- docs: add ingress example on readme
=> docs: add ingress example on readme

charts/execution-beacon/Chart.yaml, charts/execution-beacon/README.md, charts/execution-beacon/templates/statefulset.yaml
=> feat: update pvc volume claim spec

charts/generic-app/Chart.yaml, charts/generic-app/README.md, charts/generic-app/README.md.gotmpl, charts/generic-app/values.deploy.yaml, charts/generic-app/values.sts.yaml, charts/generic-app/values.yaml
- feat: remove default command to avoid confusion
=> feat: remove default command to avoid confusion

charts/generic-app/Chart.yaml, charts/generic-app/README.md, charts/generic-app/templates/_helpers.tpl, charts/generic-app/templates/deployment.yaml, charts/generic-app/templates/statefulset.yaml, charts/prometheus-rules/Chart.yaml, charts/prometheus-rules/README.md
- feat: auto reload deployment when config change
=> feat: auto reload deployment when config change

charts/prometheus-rules/Chart.yaml, charts/prometheus-rules/README.md, charts/prometheus-rules/templates/prometheus-rules.yaml
=> fix: alert annotations

CONTRIBUTING.md, charts/prometheus-rules/Chart.yaml, charts/prometheus-rules/README.md, charts/prometheus-rules/templates/prometheus-rules.yaml
=> feat: add namespace label to prometheus rules

charts/execution-beacon/Chart.yaml, charts/execution-beacon/README.md, charts/execution-beacon/templates/secret.yaml, charts/execution-beacon/templates/service.yaml, charts/execution-beacon/templates/statefulset.yaml, charts/execution-beacon/values.yaml
- feat: add gnosis chiado testnet support
- fix: invalid envFrom generation
=> feat(execution-beacon): add gnosis chiado testnet support

charts/execution-beacon/Chart.yaml, charts/execution-beacon/README.md, charts/execution-beacon/templates/statefulset.yaml
- fix: add Chiado to beacon node configuration
=> fix(execution-beacon): add Chiado network in Nimbus beacon node configuration

charts/aztec-sequencer/Chart.yaml, charts/aztec-sequencer/README.md, charts/aztec-sequencer/files/init.sh, charts/aztec-sequencer/templates/statefulset.yaml, charts/aztec-sequencer/values.yaml
- feat: add volumeMounts to init container
=> feat: update aztec-sequencer

charts/generic-app-p2p/.helmignore, charts/generic-app-p2p/Chart.yaml, charts/generic-app-p2p/README.md, charts/generic-app-p2p/README.md.gotmpl, charts/generic-app-p2p/templates/_helpers.tpl, charts/generic-app-p2p/templates/configmap.yaml, charts/generic-app-p2p/templates/ingress.yaml, charts/generic-app-p2p/templates/rbac.yaml, charts/generic-app-p2p/templates/service-p2p.yaml, charts/generic-app-p2p/templates/service.yaml, charts/generic-app-p2p/templates/serviceaccount.yaml, charts/generic-app-p2p/templates/servicemonitor.yaml, charts/generic-app-p2p/templates/statefulset.yaml, charts/generic-app-p2p/values.sts.yaml, charts/generic-app-p2p/values.yaml
- feat: add chart for generic p2p application
=> feat: add generic-app-p2p chart

charts/generic-app-p2p/Chart.yaml, charts/generic-app-p2p/README.md, charts/generic-app-p2p/values.yaml
=> feat: move exit instruction

charts/generic-app-p2p/Chart.yaml, charts/generic-app-p2p/README.md, charts/generic-app-p2p/README.md.gotmpl, charts/generic-app-p2p/values.yaml
- docs: update generic-app-p2p docs
=> docs: update generic-app-p2p docs

charts/aztec-sequencer/Chart.yaml, charts/aztec-sequencer/README.md, charts/aztec-sequencer/values.yaml
- feat: update aztec sequencers
=> feat: update aztec sequencers

charts/generic-app-p2p/Chart.yaml, charts/generic-app-p2p/README.md, charts/generic-app-p2p/README.md.gotmpl, charts/generic-app-p2p/templates/configmap.yaml, charts/generic-app-p2p/values.yaml
- feat: improve generic-app-p2p logic
=> feat: improve generic-app-p2p

charts/generic-app-p2p/Chart.yaml, charts/generic-app-p2p/README.md, charts/generic-app-p2p/templates/_helpers.tpl
- feat: remove version labels from sts which prevented versions to be upgraded without recreating the STS (immutable fields)
=> feat: remove version labels from sts

charts/generic-app-p2p/Chart.yaml, charts/generic-app-p2p/README.md, charts/generic-app-p2p/templates/_helpers.tpl, charts/generic-app/Chart.yaml, charts/generic-app/README.md, charts/generic-app/templates/_helpers.tpl
- feat: remove `chart` label when deployment type is STS, because since STS labels are immutable this prevents smooth upgrades between chart versions
=> feat: generic-app and generic-app-p2p labels

charts/execution-beacon/Chart.yaml, charts/execution-beacon/Makefile, charts/execution-beacon/README.md, charts/execution-beacon/templates/statefulset.yaml, charts/execution-beacon/values.yaml
- feat: add global volumeMounts
=> feat: add global volumeMounts

charts/generic-app/Chart.yaml, charts/generic-app/Makefile, charts/generic-app/README.md, charts/generic-app/templates/deployment.yaml, charts/generic-app/values.deploy.yaml
- feat: add strategy option to deployment
=> feat: add strategy option to deployment

charts/generic-app-p2p/Chart.yaml, charts/generic-app-p2p/README.md, charts/generic-app-p2p/templates/service-p2p.yaml
- fix: generic-app p2p externalTrafficPolicy
=> fix: generic-app p2p externalTrafficPolicy

charts/generic-app-p2p/Chart.yaml, charts/generic-app-p2p/Makefile, charts/generic-app-p2p/README.md, charts/generic-app-p2p/templates/service-p2p.yaml, charts/generic-app-p2p/values.p2p.yaml, charts/generic-app-p2p/values.yaml
- feat: option to select nodePort value
=> feat: option to select nodePort value

charts/generic-app/Chart.yaml, charts/generic-app/Makefile, charts/generic-app/README.md, charts/generic-app/README.md.gotmpl, charts/generic-app/templates/service.yaml, charts/generic-app/values.yaml
- fix: added logic for extra container ports
=> fix: update service logic for extraContainersPorts

charts/validator-ejector/.helmignore, charts/validator-ejector/Chart.yaml, charts/validator-ejector/README.md, charts/validator-ejector/templates/_helpers.tpl, charts/validator-ejector/templates/configmap.yaml, charts/validator-ejector/templates/ingress.yaml, charts/validator-ejector/templates/service.yaml, charts/validator-ejector/templates/serviceaccount.yaml, charts/validator-ejector/templates/servicemonitor.yaml, charts/validator-ejector/templates/statefulset.yaml, charts/validator-ejector/values.yaml
=> feat: add validator ejector

charts/validator-ejector/Chart.yaml, charts/validator-ejector/README.md, charts/validator-ejector/templates/statefulset.yaml
=> fix: validator-ejector env

charts/erpc/Chart.yaml, charts/erpc/README.md, charts/erpc/templates/_helpers.tpl, charts/erpc/templates/deployment.yaml, charts/erpc/values.yaml
- Added `restartOnChanges` flag to auto-trigger restarts on changes in `values.yaml` and avoid manual restarts being overlooked.
=> feat: Add restart flag for erpc chart

charts/generic-app/Chart.yaml, charts/generic-app/README.md, charts/generic-app/templates/httproute.yaml, charts/generic-app/templates/ingress.yaml, charts/generic-app/values.yaml
- feat: add support for HTTPRoute
=> feat: add support for HTTPRoute on generic app

charts/charon/Chart.yaml, charts/charon/README.md, charts/charon/values.yaml
=> fix default enr pk file path

charts/execution-beacon/Chart.yaml, charts/execution-beacon/README.md, charts/execution-beacon/templates/_helpers-execution.yaml, charts/execution-beacon/templates/configmap.yaml, charts/execution-beacon/values.yaml
=> Execution beacon/fix init

charts/execution-beacon/Chart.yaml, charts/execution-beacon/README.md, charts/execution-beacon/scripts/init-nodeport.sh, charts/execution-beacon/templates/_helpers-beacon.yaml, charts/execution-beacon/templates/_helpers-execution.yaml
=> udpate docs
